name: ilovemytank
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6083676654379815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0e13'
    - '#e1dfe0'
    - '#5c4c3d'
    - '#98b1b5'
    - '#3f8944'
  brandStrength: 1
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 0.8785590194165707
purpose: []
